stages:
     - build
     - test
     - deploy
     - post deploy

variables:
     APP_BASE_URL: http://codesis-propstone-test.s3-website-us-east-1.amazonaws.com

build website:
     image: node:16-alpine
     stage: build
     script:
          - npm i
          - CI=false npm run build
     artifacts:
          paths:
               - build

.test website:
     image: node:16-alpine
     stage: test


deploy to S3:
     stage: deploy
     image:
          name: amazon/aws-cli:2.4.11
          entrypoint: [""]
     script:
           - aws --version
           - aws s3 sync build s3://$AWS_S3_BUCKET --delete

.production tests:
     stage: post deploy
     image: curlimages/curl
     rules:
          - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
     script: 
          - curl $APP_BASE_URL | grep "React App"
